<xsl:stylesheet version="1.0" exclude-result-prefixes="asp ucidb" xmlns:ucidb="http://www.piet.nl" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:asp="urn:schemas-microsoft-com:datatypes"><xsl:template match="frame" mode="frame"><xsl:choose><xsl:when test="@IsAdded='True'"><ins><span class="addeditem"><xsl:if test="@XlinkId!='' and $releaseoutputmode='1'"><xsl:text disable-output-escaping="yes">&lt;div id="</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">"  onmouseenter ="setXlinkStyle('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">',true)"  onmouseleave="setXlinkStyle('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">',false)" onclick="selectXlinkNode('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">');" class="xsltaddxlinkselector_parent"&gt;</xsl:text></xsl:if>  <xsl:if test="@layout='Normaal 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Kader 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Kader 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 3 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_threecolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Kader 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader  mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Kader 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader  mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 3 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_threecolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 4 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>

<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column4/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column4"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if><xsl:if test="@XlinkId!='' and $releaseoutputmode='1'"><xsl:text disable-output-escaping="yes">&lt;/div&gt;</xsl:text></xsl:if></span></ins></xsl:when><xsl:when test="@IsDeleted='True'"><del><span class="deleteditem"><xsl:if test="@XlinkId!='' and $releaseoutputmode='1'"><xsl:text disable-output-escaping="yes">&lt;div id="</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">"  onmouseenter ="setXlinkStyle('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">',true)"  onmouseleave="setXlinkStyle('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">',false)" onclick="selectXlinkNode('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">');" class="xsltaddxlinkselector_parent"&gt;</xsl:text></xsl:if>  <xsl:if test="@layout='Normaal 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Kader 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Kader 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 3 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_threecolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Kader 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader  mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Kader 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader  mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 3 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_threecolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 4 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>

<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column4/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column4"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if><xsl:if test="@XlinkId!='' and $releaseoutputmode='1'"><xsl:text disable-output-escaping="yes">&lt;/div&gt;</xsl:text></xsl:if></span></del></xsl:when><xsl:otherwise><xsl:if test="@XlinkId!='' and $releaseoutputmode='1'"><xsl:text disable-output-escaping="yes">&lt;div id="</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">"  onmouseenter ="setXlinkStyle('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">',true)"  onmouseleave="setXlinkStyle('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">',false)" onclick="selectXlinkNode('</xsl:text><xsl:value-of select="@XlinkId"/><xsl:text disable-output-escaping="yes">');" class="xsltaddxlinkselector_parent"&gt;</xsl:text></xsl:if>  <xsl:if test="@layout='Normaal 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Kader 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Kader 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 3 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_threecolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Kader 1 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader  mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Kader 2 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_kader  mod visual nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_twocolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0 or count(column3/child::node())>0"><div class="nw_twocolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><div class="nw_kader_clear"><xsl:comment>DNC</xsl:comment></div><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='icon: Normaal 3 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>
<xsl:apply-templates mode="frameline" select="framemenu"></xsl:apply-templates>
<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_threecolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_threecolumn  nw_lastcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div><p class="back_to_top"><a href="#content">Naar boven</a></p></xsl:if>
</xsl:if>  <xsl:if test="@layout='Normaal 4 Koloms'"><xsl:variable name="childcount" select="count(column1/*)+count(column2/*)+count(column3/*)+count(column4/*)+count(column5/*)"></xsl:variable>

<xsl:if test="framelabel/@visibilityinframe='visible'"><h2 class="textFrameLabel"><xsl:if test="framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline'"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:value-of select="framelabel/text()"></xsl:value-of></h2></xsl:if>
<xsl:if test="$childcount>0"><div class="nw_information_tekst_container"><xsl:if test="framelabel/@visibilityinframe='hidden' and(framemenu/@layout='visible' or framemenu/@layout='visible_newline' or framemenu/@layout='visible_noline' or framemenu/@layout='visible_newline_noline')"><xsl:attribute name="id"><xsl:apply-templates mode="get_frame_id" select="frameid"></xsl:apply-templates></xsl:attribute></xsl:if><xsl:if test="count(column1/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column1"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column2/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column2"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column3/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column3"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:if test="count(column4/child::node())>0"><div class="nw_fourcolumn"><xsl:apply-templates mode="column" select="column4"></xsl:apply-templates><xsl:comment>DNC</xsl:comment></div></xsl:if><xsl:comment>DNC</xsl:comment></div></xsl:if>
</xsl:if><xsl:if test="@XlinkId!='' and $releaseoutputmode='1'"><xsl:text disable-output-escaping="yes">&lt;/div&gt;</xsl:text></xsl:if></xsl:otherwise></xsl:choose></xsl:template>
</xsl:stylesheet>