<xsl:stylesheet version="1.0" exclude-result-prefixes="asp ucidb" xmlns:ucidb="http://www.piet.nl" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:asp="urn:schemas-microsoft-com:datatypes"><xsl:template match="documenttitle" mode="documenttitle"><xsl:choose><xsl:when test="@IsAdded='True'"><ins><span class="addeditem">  <xsl:if test="@layout='Titel onderwerp'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h2 class="textClass"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h2></xsl:if>
</xsl:if>  <xsl:if test="@layout='Titel rubriek'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h2 class="textSection"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h2></xsl:if>
</xsl:if>  <xsl:if test="@layout='Titel document'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h1 class="textTitle"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h1></xsl:if>
</xsl:if></span></ins></xsl:when><xsl:when test="@IsDeleted='True'"><del><span class="deleteditem">  <xsl:if test="@layout='Titel onderwerp'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h2 class="textClass"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h2></xsl:if>
</xsl:if>  <xsl:if test="@layout='Titel rubriek'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h2 class="textSection"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h2></xsl:if>
</xsl:if>  <xsl:if test="@layout='Titel document'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h1 class="textTitle"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h1></xsl:if>
</xsl:if></span></del></xsl:when><xsl:otherwise>  <xsl:if test="@layout='Titel onderwerp'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h2 class="textClass"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h2></xsl:if>
</xsl:if>  <xsl:if test="@layout='Titel rubriek'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h2 class="textSection"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h2></xsl:if>
</xsl:if>  <xsl:if test="@layout='Titel document'"><xsl:if test="(count(child::node())+count(child::text()))>0"><h1 class="textTitle"><xsl:apply-templates mode="documenttitlecontainer" select="."></xsl:apply-templates></h1></xsl:if>
</xsl:if></xsl:otherwise></xsl:choose></xsl:template>
</xsl:stylesheet>